import "dotenv/config";
import { chromium } from "playwright-core";

const BASE = process.env.PROBE_URL ?? "http://localhost:5173";
const b = await chromium.launch({ channel: "chrome", headless: true });
const p = await (await b.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
p.on("console", (m) => { if (m.type() === "error") console.log("CONSOLE-ERR:", m.text().slice(0, 400)); });
p.on("response", (r) => { if (r.url().includes("/trpc")) console.log("TRPC", r.status(), decodeURIComponent(r.url()).slice(0, 240)); });
await p.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await p.fill("#username", "owner");
await p.fill("#password", process.env.OWNER_PASSWORD ?? "nusa2026");
await p.click("button[type=submit]");
await p.waitForTimeout(2500);
await p.goto(`${BASE}/pos`, { waitUntil: "networkidle" });
await p.fill('input[aria-label="Cari produk"]', "Beras");
await p.waitForTimeout(1500);
const cards = await p.locator(".grid button").count();
const bodyTxt = (await p.textContent("body"))?.replace(/\s+/g, " ").slice(0, 260);
console.log("CARDS:", cards, "| BODY:", bodyTxt);
await b.close();
